apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: preflight
  namespace: playground
spec:
  params:
    - default: 'false'
      name: preflight_results_exists
      type: string
  results:
    - description: ''
      name: log_output_file
    - description: ''
      name: result_output_file
    - description: ''
      name: artifacts_output_dir
  steps:
    - image: 'quay.io/redhat-isv/operator-pipelines-images:latest'
      name: preflight-tests
      resources: {}
      script: |
        #! /usr/bin/env bash
        PREFLIGHT_RESULTS_EXISTS="$(params.preflight_results_exists)"
        if [ $PREFLIGHT_RESULTS_EXISTS == "true" ]; then
          echo "Preflight results already exists- skipping"
          echo -n "none" | tee $(results.log_output_file.path)
          echo -n "none" | tee $(results.result_output_file.path)
          exit 0
        fi

        echo "Testing"

        # Temporary test data
        ls -l
        cp -r /home/user/tests/data/* .
        ls -l


        echo -n preflight.log | tee $(results.log_output_file.path)
        echo -n results.json | tee $(results.result_output_file.path)
        echo -n artifacts | tee $(results.artifacts_output_dir.path)
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source